# Generated by Django 2.0.1 on 2018-02-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20180201_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gallon_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
